
name: CI
on:
  create: 
    - tags: 
    - 'ios*'


#on: 
#  push:
#    tags:
#    - 'ios*'
#    - '*-Production'
#    - '*-Stageing'
#      - ios*
#    - '*-Production'
#    - '*-Stageing'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
